#+ endpoint: https://aopwiki.rdf.bigcat-bioinformatics.org/sparql/

PREFIX aop: <https://identifiers.org/aop/>
PREFIX aop.events: <https://identifiers.org/aop.events/>
PREFIX aop.relationships: <https://identifiers.org/aop.relationships/>
PREFIX aop.stressor: <https://identifiers.org/aop.stressor/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX as: <https://www.w3.org/ns/activitystreams#>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX cas: <https://identifiers.org/cas/>
PREFIX chebi: <https://identifiers.org/chebi/>
PREFIX chebio: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chembl.compound: <https://identifiers.org/chembl.compound/>
PREFIX cheminf: <http://semanticscience.org/resource/CHEMINF_>
PREFIX chemspider: <https://identifiers.org/chemspider/>
PREFIX cl: <http://purl.obolibrary.org/obo/CL_>
PREFIX comptox: <https://comptox.epa.gov/dashboard/>
PREFIX dawgt: <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX drugbank: <https://identifiers.org/drugbank/>
PREFIX edam: <http://edamontology.org/>
PREFIX ensembl: <https://identifiers.org/ensembl/>
PREFIX fma: <http://purl.org/sig/ont/fma/fma>
PREFIX fn: <http://www.w3.org/2005/xpath-functions/#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX formats: <http://www.w3.org/ns/formats/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX go: <http://purl.org/obo/owl/GO#>
PREFIX gqi: <http://www.openlinksw.com/schemas/graphql/intro#>
PREFIX gql: <http://www.openlinksw.com/schemas/graphql#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX hgnc: <https://identifiers.org/hgnc/>
PREFIX hmdb: <https://identifiers.org/hmdb/>
PREFIX hp: <http://purl.obolibrary.org/obo/HP_>
PREFIX inchikey: <https://identifiers.org/inchikey/>
PREFIX kegg.compound: <https://identifiers.org/kegg.compound/>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX lipidmaps: <https://identifiers.org/lipidmaps/>
PREFIX math: <http://www.w3.org/2000/10/swap/math#>
PREFIX mesh: <http://purl.org/commons/record/mesh/>
PREFIX mf: <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX mi: <http://purl.obolibrary.org/obo/MI_>
PREFIX mmo: <http://purl.obolibrary.org/obo/MMO_>
PREFIX mp: <http://purl.obolibrary.org/obo/MP_>
PREFIX nbo: <http://purl.obolibrary.org/obo/NBO_>
PREFIX ncbigene: <https://identifiers.org/ncbigene/>
PREFIX ncbitaxon: <http://purl.bioontology.org/ontology/NCBITAXON/>
PREFIX nci: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX obo: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX ogc: <http://www.opengis.net/>
PREFIX ogcgml: <http://www.opengis.net/ont/gml#>
PREFIX ogcgs: <http://www.opengis.net/ont/geosparql#>
PREFIX ogcgsf: <http://www.opengis.net/def/function/geosparql/#>
PREFIX ogcgsr: <http://www.opengis.net/def/rule/geosparql/#>
PREFIX ogcsf: <http://www.opengis.net/ont/sf#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX pato: <http://purl.obolibrary.org/obo/PATO_>
PREFIX pav: <http://purl.org/pav/>
PREFIX pco: <http://purl.obolibrary.org/obo/PCO_>
PREFIX pr: <http://purl.obolibrary.org/obo/PR_>
PREFIX product: <http://www.buy.com/rss/module/productV2/>
PREFIX protseq: <http://purl.org/science/protein/bysequence/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pubchem.compound: <https://identifiers.org/pubchem.compound/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfa: <http://www.w3.org/ns/rdfa#>
PREFIX rdfdf: <http://www.openlinksw.com/virtrdf-data-formats#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sc: <http://purl.org/science/owl/sciencecommons/>
PREFIX scovo: <http://purl.org/NET/scovo#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sql: <http://www.openlinksw.com/schemas/sql#>
PREFIX stat: <http://www.w3.org/ns/posix/stat#>
PREFIX uberon: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX uniprot: <https://identifiers.org/uniprot/>
PREFIX vcard: <http://www.w3.org/2001/vcard-rdf/3.0#>
PREFIX vcard2006: <http://www.w3.org/2006/vcard/ns#>
PREFIX virtcxml: <http://www.openlinksw.com/schemas/virtcxml#>
PREFIX virtrdf: <http://www.openlinksw.com/schemas/virtrdf#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX vt: <http://purl.obolibrary.org/obo/VT_>
PREFIX wikidata: <https://identifiers.org/wikidata/>
PREFIX xf: <http://www.w3.org/2004/07/xpath-functions#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xsl10: <http://www.w3.org/XSL/Transform/1.0#>
PREFIX xsl1999: <http://www.w3.org/1999/XSL/Transform#>
PREFIX xslwd: <http://www.w3.org/TR/WD-xsl#>
PREFIX yago: <http://dbpedia.org/class/yago/>


SELECT ?AO ?AOname ?AOP (CONCAT('"',GROUP_CONCAT(?ChemicalName;SEPARATOR='","'),'"') AS ?ChemicalNames) WHERE {
  ?AO a aopo:KeyEvent ; 
  dc:identifier ?AOLookup ; 
  dc:title ?AOname . 
  ?AOP a aopo:AdverseOutcomePathway ; 
  aopo:has_adverse_outcome ?AOLookup ;
  nci:C54571 ?Stressor .
  ?Stressor dc:title ?StressorName.
  OPTIONAL {?Stressor aopo:has_chemical_entity ?Chemical. 
            ?Chemical dc:title ?ChemicalName.}
  FILTER regex (?AOname, "fibrosis", "i")}
  ORDER BY DESC (?AO)
