#+ summary: Returns the Adverse outcome for MIE.
#+ endpoint: https://aopwiki.rdf.bigcat-bioinformatics.org/sparql/
#+ tags:
#+   - AOP
#+ defaults:
#+   - MIE: https://identifiers.org/aop.events/18



PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?MIEwebpage ?MolecularInitiatingEventName ?AOwebpage  ?AdverseOutcomeName WHERE { 
  ?MIEwebpage dc:identifier ?MIELookup ; 
  dc:title ?MolecularInitiatingEventName . 
  ?AOPwebpage a aopo:AdverseOutcomePathway ; 
  aopo:has_molecular_initiating_event ?MIELookup; 
  aopo:has_adverse_outcome ?AOwebpage. 
  ?AOwebpage dc:title ?AdverseOutcomeName .
  FILTER (?MIEwebpage = ?__MIE_iri)
}
