#+ summary: Returns nanopublication based on AOP title
#+ endpoint: http://blaze.aopsketchpad.insilicohub.org/blazegraph/sparql
#+ tags:
#+   - AOP-SKETCHPAD

PREFIX ntemplate: <https://w3id.org/np/o/ntemplate/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX aopdo: <https://w3id.org/aopdo/>

SELECT ?nanopubURI ?AOPTitle
WHERE {
  GRAPH ?assertionId {
    aopdo:AOP aopdo:hasTitle ?AOPTitle ;
    
    # Case-insensitive regex search on AOPTitle
    FILTER(REGEX(?AOPTitle, ?_AOPTitle, "i"))
  }
        
  # Extract portion before the suffix (assumed to be '#')
  BIND(STRBEFORE(STR(?assertionId), "#") AS ?nanopubURI)
}
